// frontend/angular/src/app/shared/components/layout/header/header.component.ts
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';
import { TokenService } from '../../../../core/services/token/token.service';
import { UserService } from '../../../../core/services/auth/user.service';
import { SHARED_ROUTES } from '../../../../core/constants/shared.routes';
import { User } from '../../../../core/models/Users/user.model';

@Component({
    selector: 'app-header',
    standalone: true,
    imports: [RouterModule, CommonModule],
    templateUrl: './header.component.html',
    styleUrls: ['./header.component.scss']
})
export class HeaderComponent {
    menuOpen = false;
    routes = SHARED_ROUTES;
    profileMenuOpen = false;
    user!: User;
    
    constructor(
        public tokenService: TokenService,
        private userService: UserService,
    ) {}
    
    
    ngOnInit() {
        if (this.tokenService.isAuthenticated()) {
            const userInfo = this.tokenService.getUserInfo();
            if (userInfo) {
                this.user = userInfo;
            }
        }
    }

    toggleProfileMenu() {
        // console.log('toggleProfileMenu called', this.user);
        this.profileMenuOpen = !this.profileMenuOpen;
    }

    toggleMenu() {
        this.menuOpen = !this.menuOpen;
    }

    logout() {
        this.userService.logout();
        this.tokenService.clearAll();
        window.location.href = this.routes.NEXT.HOME;
    }
}

<header class="header">
    <div class="container">
        <div class="logo">
            <a [href]="routes.NEXT.HOME">
                <img src="/Logo_VitalNest.png" alt="VitalNest Logo" />
            </a>
        </div>
        <button class="hamburger" (click)="toggleMenu()" aria-label="Toggle menu">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
        </button>
        <nav class="nav" [class.navOpen]="menuOpen">
            <ul class="navList">
                <li class="navItem">
                    <a [href]="routes.NEXT.HOME" class="navLink" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}">Página Principal</a>
                </li>
                <li class="navItem">
                    <a [href]="routes.NEXT.SHOP + '?activity_type=1'" class="navLink" routerLinkActive="active">Actividades</a>
                </li>
                <li class="navItem">
                    <a [href]="routes.NEXT.MEALS + '?type_meal=1'" class="navLink" routerLinkActive="active">Menús</a>
                </li>

                <!-- 🔹 NUEVA OPCIÓN PARA PAGOS -->
                <li class="navItem">
                    <a [routerLink]="'/payments'" class="navLink" routerLinkActive="active">Pagos</a>
                </li>

                <li class="navItem" *ngIf="!tokenService.isAuthenticated()">
                    <a [routerLink]="routes.ANGULAR.AUTH.LOGIN" class="navLink auth-button">Login</a>
                </li>
                <li class="navItem profile-container" *ngIf="tokenService.isAuthenticated()">
                    <div class="profile-trigger" (click)="toggleProfileMenu()">
                        <ng-container *ngIf="user?.profile_img; else defaultIcon">
                            <img [src]="user.profile_img" alt="Profile" class="profile-image"/>
                        </ng-container>
                        <ng-template #defaultIcon>
                            <i class="fas fa-user profile-icon"></i>
                        </ng-template>
                    </div>
                    <div class="profile-dropdown" [class.show]="profileMenuOpen">
                        <div class="profile-header">
                            <ng-container *ngIf="user?.profile_img; else dropdownDefaultIcon">
                                <img [src]="user.profile_img" alt="Profile" class="dropdown-profile-image"/>
                            </ng-container>
                            <ng-template #dropdownDefaultIcon>
                                <i class="fas fa-user profile-icon"></i>
                            </ng-template>
                            <div class="profile-info">
                                <p class="profile-name">{{user.name}}</p>
                                <p class="profile-email">{{user.email}}</p>
                            </div>
                        </div>
                        <div class="profile-menu">
                            <a [routerLink]="routes.ANGULAR.AUTH.PROFILE" class="profile-link">
                                <i class="fas fa-user"></i> Mi Perfil
                            </a>
                            <a [routerLink]="routes.ANGULAR.AUTH.FAMILY" class="profile-link">
                                <i class="fas fa-users"></i> Mis Familiares
                            </a>
                            <a [routerLink]="routes.ANGULAR.AUTH.RESERVATIONS" class="profile-link">
                                <i class="fas fa-calendar-alt"></i> Mis Reservas
                            </a>
                            <a [routerLink]="routes.ANGULAR.AUTH.PAYMENTS" class="profile-link">
                                <i class="fas fa-credit-card"></i> Mis Pagos
                            </a>
                            <a (click)="logout()" class="profile-link logout">
                                <i class="fas fa-sign-out-alt"></i> Cerrar Sesión
                            </a>
                        </div>
                    </div>
                </li>
            </ul>
        </nav>
    </div>
</header>

// fullstack/next/src/components/layout/Header.tsx
'use client';

import Link from 'next/link';
import { useState, useEffect } from 'react';
import styles from '../../styles/layout/Header.module.css';
import { SHARED_ROUTES, UserData,  DEFAULT_USER } from '@/store/Constants';
import { isAuthenticated, logout, authListener, getUserInfo } from '../../utils/auth';

const Header: React.FC = () => {
  const [menuOpen, setMenuOpen] = useState(false);
  const [isAuth, setIsAuth] = useState(false);
  const [user, setUser] = useState<UserData>(DEFAULT_USER);
  const [profileMenuOpen, setProfileMenuOpen] = useState(false);



  useEffect(() => {
    setIsAuth(isAuthenticated());
      const userInfo = getUserInfo();
      if (userInfo) {
        setUser(userInfo);
      }
      const cleanup = authListener((newAuthState) => {
        setIsAuth(newAuthState);
      });
    return cleanup;
  }, []);


  const toggleMenu = () => {
    setMenuOpen(!menuOpen);
  };

  const toggleProfileMenu = () => {
    setProfileMenuOpen(!profileMenuOpen);
  };

  return (
    <header className={styles.header}>
      <div className={styles.container}>
        <div className={styles.logo}>
          <Link href={SHARED_ROUTES.NEXT.HOME}>
            <img src="/Logo_VitalNest.png" alt="VitalNest Logo" />
          </Link>
        </div>
        <button className={styles.hamburger} onClick={toggleMenu} aria-label="Toggle menu">
          <span className={styles.bar}></span>
          <span className={styles.bar}></span>
          <span className={styles.bar}></span>
        </button>
        <nav className={`${styles.nav} ${menuOpen ? styles.navOpen : ''}`}>
          <ul className={styles.navList}>
            <li className={styles.navItem}>
              <Link href={SHARED_ROUTES.NEXT.HOME} className={styles.navLink}>
                Página Principal
              </Link>
            </li>
            <li className={styles.navItem}>
              <Link href={`${SHARED_ROUTES.NEXT.SHOP}?activity_type=1`} className={styles.navLink}>
                Actividades
              </Link>
            </li>
            <li className={styles.navItem}>
              <Link href={`${SHARED_ROUTES.NEXT.MEALS}?type_meal=1`} className={styles.navLink}>
                Menús
              </Link>
            </li>

            {!isAuth ? (
              <li className={styles.navItem}>
                <Link 
                  href={SHARED_ROUTES.ANGULAR.AUTH.LOGIN} 
                  className={`${styles.navLink} ${styles.authButton}`}
                >
                  Login
                </Link>
              </li>
            ) : (
              <li className={`${styles.navItem} ${styles.profileContainer}`}>
                <div className={styles.profileTrigger} onClick={toggleProfileMenu}>
                  {user?.profile_img ? (
                    <img 
                      src={user.profile_img} 
                      alt="Profile" 
                      className={styles.profileImage}
                    />
                  ) : (
                    <i className={`fas fa-user ${styles.profileIcon}`}></i>
                  )}
                </div>

                <div className={`${styles.profileDropdown} ${profileMenuOpen ? styles.show : ''}`}>
                  <div className={styles.profileHeader}>
                    {user?.profile_img ? (
                      <img 
                        src={user.profile_img} 
                        alt="Profile" 
                        className={styles.dropdownProfileImage}
                      />
                    ) : (
                      <i className={`fas fa-user ${styles.profileIcon}`}></i>
                    )}
                    <div className={styles.profileInfo}>
                      <p className={styles.profileName}>{user?.name}</p>
                      <p className={styles.profileEmail}>{user?.email}</p>
                    </div>
                  </div>
                  <div className={styles.profileMenu}>
                    <Link 
                      href={SHARED_ROUTES.ANGULAR.AUTH.PROFILE} 
                      className={styles.profileLink}
                    >
                      <i className="fas fa-user"></i> Mi Perfil
                    </Link>
                    <Link 
                      href={SHARED_ROUTES.ANGULAR.AUTH.FAMILY} 
                      className={styles.profileLink}
                    >
                      <i className="fas fa-users"></i> Mis Familiares
                    </Link>
                    <Link 
                      href={SHARED_ROUTES.ANGULAR.AUTH.RESERVATIONS} 
                      className={styles.profileLink}
                    >
                      <i className="fas fa-calendar-alt"></i> Mis Reservas
                    </Link>
                    <Link 
                      href={SHARED_ROUTES.ANGULAR.AUTH.PAYMENTS} 
                      className={styles.profileLink}
                    >
                      <i className="fas fa-credit-card"></i> Mis Pagos
                    </Link>
                    <a 
                      href="#" 
                      onClick={(e) => {
                        e.preventDefault();
                        window.location.href = SHARED_ROUTES.ANGULAR.AUTH.LOGOUT;
                      }} 
                      className={`${styles.profileLink} ${styles.logout}`}
                    >
                      <i className="fas fa-sign-out-alt"></i> Cerrar Sesión
                    </a>
                  </div>
                </div>
              </li>
            )}

          </ul>
        </nav>
      </div>
    </header>
  );
};

export default Header;
